[package]
name = "dataencoded/wafflehouse"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.4.7"
promise = "evaera/promise@4.0.0"
signal = "sleitnick/signal@^1"
symbol = "sleitnick/symbol@^2"
component = "sleitnick/component@^2"
option = "sleitnick/option@^1"
loader = "sleitnick/loader@^1"
trove = "sleitnick/trove@^0"